
var GAME_LEVELS = [
  ["                                             xxxx                               ",
   "                                                                                ",
   "                                                                                ",
   "                                                             ooo                ",
   "                                                            o   o            ooo",
   "                                              oo      oooooo     ooooooooooooooo",
   "                                                      xxxxxx     xxxxxxxxxxxxxxx",
   "                                                                             xxx",
   "                                            xx  xx                           xxx",
   "                                       ooo                                   xxx",
   "                                       ooo          xx                       xxx",
   "                                       xxx                                   xxx",
   "                                                             o               xxx",
   "                                                    o     xxxxo              xxx",
   "                                                               o             xxx",
   "  xx        xxx                     o                           o            xxx",
   "  x         |||      u                xxx   x || x    xxxxxxxxxxxx           xxx",
   "  x                          o              x||||x                           xxx",
   "  x                             xxx         x!!!!x                           xxx",
   "  x                                         x!!!!x                           xxx",
   "  x                      xxx                x!!!!x                           xxx",
   "  x  @                                      x!!!!x                           xxx",
   "  xxxxxxxxxx   x   j   x                  xxxxxxxxxx                         xxx",
   "           x   xxxxxxxxx                 xxxxxxxxxxxx                        xxx",
   "           x!!!x       x!!!!!!!!!!!!!!!!!xxxxxxxxxxxx!!!!!!!!!!!!!!!!!!!!!!!!xxx",
   "           x!!!x       x!!!!!!!!!!!!!!!!!xxxxxxxxxxxx!!!!!!!!!!!!!!!!!!!!!!!!xxx",
   "           xxxxx       xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "                                                                                ",
   "                                                                                "],

 [ "  x             !x                                                               x                  !x                             xxx",
   "  x     o       !x                                                               x                  !x                             xxx",
   "  x     x       !x                                                               x                  !x                             xxx",
   "  x     x!      !x                                                               x                  !x                             xxx",
   "  x     x!      !x                           ooooooooooooooo                     x                  !x                             xxx",
   "  x    ox!=     !x                           xxxxxxxxxxxxxxx                     x                  !x                             xxx",
   "  x    xx!=     !x                    oo                         oo              x                  !x                             xxx",
   "  x     x!      !x                   xxxx                       xxxx             x        xxx   o   !x                             xxx",
   "  x     x!      !x                                =xxx=                          x        xxx!  o   !x                             xxx",
   "  xo    x!      !x                                =xxx=                          x       oxxx!  o   !x                             xxx",
   "  xx    x!   xxx!x            oo                  =xxx=                  oo      x       xxxx!  o   !x                             xxx",
   "  x     x!      !x           xxxx                                       xxxx     x       xxxx!  o   !x                             xxx",
   "  x     x!      !x                                                               x      oxxxx!  o   !x                             xxx",
   "  x    ox!      !x                    oo                         oo              x      xxxxx!  o   !x                             xxx",
   "  x    xx!      !x                   xxxx                       xxxx             x      xxxxx!  o   !x                             xxx",
   "  x     x!      !x                                                               x     oxxxxx!  o   !x                             xxx",
   "  x     x!     =!x                                       oo                      x     xxxxxx!  o   !x                             xxx",
   "  xo    x!     =!x                           xxxx       xxxx                     x     xxxxxx!  o   !x                             xxx",
   "  xx    x!      !x                             =x       x=                       x    oxxxxxx!  o   !x                             xxx",
   "  x     x!      !x                    oo       =x       x=       oo              x    xxxxxxx!  o   !x             oo              xxx",
   "  x     x!      !x                   xxxx                       xxxx             x    xxxxxxx!  o   !x            oooo             xxx",
   "  x    ox!      !x                                                               x   oxxxxxxx!  o   !x           oooooo            xxx",
   "  x    xx!      !x            oo                                         oo      x   xxxxxxxx!  o   !x           xxxxxx            xxx",
   "  x     x!                   xxxx                                       xxxx         xxxxxxxx!  o                                  xxx",
   "  x     x!                                                                          oxxxxxxxx!  o                                  xxx",
   "  x @   x!               j                                    j                     xxxxxxxxx!  o                                  xxx",
   "  xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx                   xxxxxxxxxx",
   "                                                                                                        x= ooooooooooooooo  x         ",
   "                                                                                                        xxxxxxxxxxxxxxxxxxxxx         "],  

["x          xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
"x          x                                                                                                                                    x",
"x    @     x                                                                                                                                    x",
"x          x                                                                                                                                    x",
"x          x                                                                                                                                    x",
"xxx      xxx                                  oo               oo              oo              oo              oo                               x",
"x          x                              xx     j                  j                 j                 j                      xx               x",
"x    o     x                              xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx               x",
"x          x                              xx                                                                                    x               x",
"xxx      xxx                          xx  xx                                                                                    x               x",
"x          x                          xx||xx                                                                                    xxxxxxxx        x",
"x    o     x                      xx  xx!!xx                                                                                    x=              x",
"x          x                      xx||xx!!xx                                                                                    x               x",
"xxx      xxx                  xx  xx!!xx!!xx                                                                                    x               x",
"x          x                  xx||xx!!xx!!xx                                                                                    x        xxxxxxxx",
"x    o     x              xx  xx!!xx!!xx!!xx                                                                                    x              =x",
"x          x              xx||xx!!xx!!xx!!xx                                                                                    x               x",
"xxx      xxx          xx  xx!!xx!!xx!!xx!!xx                                                                                    x               x",
"x          x          xx||xx!!xx!!xx!!xx!!xx                                                                                    xxxxxxxx        x",
"x    o     x      xx  xx!!xx!!xx!!xx!!xx!!xx                                                                                    x=              x",
"x          x      xx||xx!!xx!!xx!!xx!!xx!!xx                   o       o        o         o       o                             x               x",
"xxx      xxx   o  xx!!xx!!xx!!xx!!xx!!xx!!xx                     o   o         o o          o   o                               x               x",
"x          x   o  xx!!xx!!xx!!xx!!xx!!xx!!xx                       o          o   o           o                                 x        xxxxxxxx",
"x    o     x   o  xx!!xx!!xx!!xx!!xx!!xx!!xx                 xx    o         ooooooo          o     xx                          x              =x",
"x          x   o  xx!!xx!!xx!!xx!!xx!!xx!!xx                       o        o  xxx  o         o                                 x               x",
"xxx      xxx   o  xx!!xx!!xx!!xx!!xx!!xxxxxx           j           o       o         o        o                     xx          x               x",
"x          x   o  xx!!xx!!xx!!xx!!xx!!xx||xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx          xxxxxxxx        x",
"x    o     x   o  xx!!xx!!xx!!xx!!xxxxxx                                                                                        x=              x",
"x          x   o  xx||xx!!xx!!xxxxxx||xx                                                                                        x               x",
"xxx      xxx   o      xx||xx!!xx||xx                                                                                          xxx               x",
"x          x   o          xx||xx                                                                                           xxxxxx        xxxxxxxx",
"x          x   o                                                                                                        xxxxxxxxx              =x",
"x    o     x                                                                                                         xxxxxxxxxxxx               x",
"x          x                  j                                     j                         j                   xxxxxxxxxxxxxxx               x",
"xxx      xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx        x",
"x                                  ||                                         ||                                     ||                         x",
"x                         ||                                                                                                 ||                 x",
"x                                                                                                                                               x",
"x                                                 ooo               ooo                ooo              ooo                              xxxxxxxx",
"x                                                                                                                                               x",
"x                                         ||                ||                                  ||                                              x",
"xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx!!!!xxxxxxxxxxxxxx!!!!xxxxxxxxxxxxxx!!!!xxxxxxxxxxxxxx!!!!xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"]
];


if (typeof module != "undefined" && module.exports)
  module.exports = GAME_LEVELS;



